server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kkachi
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    open-in-view: false
  data:
    redis:
      port: 6379
      host: localhost
      password: